version: '3'

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: senha
    ports:
      - "27017:27017"

  api:
    build: .
    volumes:
      - .:/app
    ports: 
      - " :5170"
      - "7293:7293"
      
    command: "dotnet run"